Bangazon/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Bangazon.Models
{
  public class Order
  {
    [Key]
    public int OrderId {get;set;}

    [Required]
    [DataType(DataType.Date)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime DateCreated {get;set;}

    [DataType(DataType.Date)]
    public DateTime? DateCompleted {get;set;}

    [Required]
    public string UserId {get; set;}

    [Required]
    public ApplicationUser User { get; set; }

    public int? PaymentTypeId {get;set;}
    public PaymentType PaymentType {get;set;}

    public virtual ICollection<OrderProduct> OrderProducts { get; set; }
  }
}

Bangazon/Controllers/PaymentTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bangazon.Data;
using Bangazon.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Bangazon.Controllers
{
    public class PaymentTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

       


        public PaymentTypesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: PaymentTypes
        [Authorize]
        //constructor type of paymenttype
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.PaymentType.Include(p => p.User);

            var user = await GetCurrentUserAsync();

            //gets all payment types associated with the user and has and active status of true
            //returns that information to a list
            var userCheck = await _context.PaymentType.Where(p => p.UserId == user.Id && p.Active == true).ToListAsync();

            // if there are 0 payment types assocated with the user
            // or if their or no active payment types
            if (userCheck.Count() < 1 )
            {
                //redirect to a page that tells them 
                //and gives them an option to create a payment type
                return View("NoPaymentTypes");
            }

            return View(userCheck);
                //returns a view that hass all payment types associated with the user
               
        }

        // GET: PaymentTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentType = await _context.PaymentType
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PaymentTypeId == id);
            if (paymentType == null)
            {
                return NotFound();
            }

            return View(paymentType);
        }

        // GET: PaymentTypes/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: PaymentTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentTypeId,DateCreated,Description,AccountNumber,UserId,Active")] PaymentType paymentType)
        {

            //removes the user and userid so the model state doesnt think that the information is invalid
            ModelState.Remove("User");
            ModelState.Remove("UserId");
            //checks to for all the information in the model state
            if (ModelState.IsValid)
            {
                //gets the current user
                var user = await GetCurrentUserAsync();
                //grabs the current user's id
                paymentType.UserId = user.Id;
                //sets the active status to true anytime a new payment type is created
                paymentType.Active = true;
                //adds all the user and paymentType information into context
                _context.Add(paymentType);
                //saves the changes
                await _context.SaveChangesAsync();
                //redirects back to all the payment types
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", paymentType.UserId);
            return View(paymentType);
        }

        // GET: PaymentTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentType = await _context.PaymentType.FindAsync(id);
            if (paymentType == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", paymentType.UserId);
            return View(paymentType);
        }

        // POST: PaymentTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentTypeId,DateCreated,Description,AccountNumber,UserId,Active")] PaymentType paymentType)
        {
            if (id != paymentType.PaymentTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paymentType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentTypeExists(paymentType.PaymentTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", paymentType.UserId);
            return View(paymentType);
        }

        // GET: PaymentTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentType = await _context.PaymentType
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PaymentTypeId == id);
            if (paymentType == null)
            {
                return NotFound();
            }

            return View(paymentType);
        }

        // POST: PaymentTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {   
            //gets the payment type by id
            PaymentType paymentType = await _context.PaymentType.FindAsync(id);

            
            try
            {
               //it first tries to remove the payment type from the data base
                _context.PaymentType.Remove(paymentType);
                //then save the changes
                await _context.SaveChangesAsync();
            }
            // if the payment type is associated with an order
            // this catches the exception when it's active
            catch (Exception) when (paymentType.Active == true)
            {
                //changes the active status to false
                paymentType.Active = false;
                //updates the payment type since it cant be deleted
                _context.Update(paymentType);
                //saves the changes
                await _context.SaveChangesAsync();
            }

            // redirects back to the view of all payment types
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentTypeExists(int id)
        {
            return _context.PaymentType.Any(e => e.PaymentTypeId == id);
        }
    }
}

Bangazon/Views/Orders/CheckedOut.cshtml
@model Bangazon.Models.OrderViewModels.OrderEditViewModel
<div>
    @{
        //If we tried to check out with ONLY products that are out of stock, this will tell us that all the products are removed
        if (Model.Order.OrderProducts.Count() == 0)
        {
            <h1>Sorry!</h1>
            <hr />
            <h4>The items in your cart are now out of stock.</h4>
        }
        //Runs if this page is called while we still have stuff attached to the order
        else
        {
            <div>
                <h1>Your order was placed!</h1>
                @*Prints out the products that were successfully ordered, after all out-of-stock items were removed*@
                <h2>Products Ordered:</h2>
                @{
                    double TotalPrice = 0;
                    foreach (var OrderProduct in Model.Order.OrderProducts)
                    {
                        <dl class="row">
                            <dd class="col-sm-2">
                                <a asp-controller="Products" asp-action="Details" asp-route-id="@OrderProduct.ProductId">@Html.DisplayFor(model => OrderProduct.Product.Title)</a>
                            </dd>
                            <dt class="col-sm-10">
                                @Html.DisplayFor(model => OrderProduct.Product.Price)
                            </dt>
                            @{
                                TotalPrice += OrderProduct.Product.Price;
                            }
                        </dl>
                    }
                    <h4>Total Price: @TotalPrice.ToString("C2")</h4>
                }
            </div>
        }
        @*If any products were removed from the cart, we want to let the user know and list them all out!*@
        if (Model.outOfStockProducts.Count() > 0)
        {
            <hr />
            <h4>The following items were out of stock, and therefore removed from your order: </h4>
            foreach (var OrderProduct in Model.outOfStockProducts)
            {
                <dl class="row">
                    <dd class="col-sm-2">
                        <a asp-controller="Products" asp-action="Details" asp-route-id="@OrderProduct.Product.ProductId">@Html.DisplayFor(model => OrderProduct.Product.Title)</a>
                    </dd>
                </dl>
            }
        }
    }
</div>

Bangazon/Views/Orders/Create.cshtml
@model Bangazon.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateCompleted" class="control-label"></label>
                <input asp-for="DateCompleted" class="form-control" />
                <span asp-validation-for="DateCompleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PaymentTypeId" class="control-label"></label>
                <select asp-for="PaymentTypeId" class ="form-control" asp-items="ViewBag.PaymentTypeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bangazon/Views/Orders/Delete.cshtml
@model Bangazon.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentType.AccountNumber)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Bangazon/Views/Orders/Details.cshtml
@model Bangazon.Models.Order

@{
    ViewData["Title"] = "Details";
}

@*This view doubles as a way to look at our shopping cart AND view past orders*@
<div>
    @*If there's no payment type attached, this is an open order, and will be a Shopping Cart page!*@
    @if (Model.PaymentTypeId == null)
    {
        <h1>Shopping Cart</h1>
    }
    //Otherwise we're gonna show the user info from a past order
    else
    {
        <h1>Order from @Html.DisplayFor(model => model.DateCompleted)</h1>
    }
    <dl class="row">
        @*If there's no payment type, show info tied to how the user paid, who paid, where the order was sent, and what day the order was completed on*@
        @if (Model.PaymentTypeId != null)
        {
            <dt class="col-sm-2">
                Buyer
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.User.FirstName) @Html.DisplayFor(model => model.User.LastName)
            </dd>
            <dt class="col-sm-2">
                Shipping Address
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.User.StreetAddress)
            </dd>
            <dt class="col-sm-2">
                Payment Type
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentType.Description)
            </dd>
            <dt class="col-sm-2">
                Account Number
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentType.AccountNumber)
            </dd>
        }
    </dl>
    <hr />
    @{
        //Prints out all the products in our cart, if there are any
        if (Model.OrderProducts.Count() != 0)
        {
            double TotalPrice = 0;
            foreach (var OrderProduct in Model.OrderProducts)
            {
                <dl class="row">
                    <dd class="col-sm-2">
                        <a asp-controller="Products" asp-action="Details" asp-route-id="@OrderProduct.ProductId">@Html.DisplayFor(model => OrderProduct.Product.Title)</a>
                    </dd>
                    <dt class="col-sm-10">
                        @Html.DisplayFor(model => OrderProduct.Product.Price)
                    </dt>
                    @{
                        TotalPrice += OrderProduct.Product.Price;
                    }
                </dl>
            }
            <h4>Total Price: @TotalPrice.ToString("C2")</h4>
        }
        //If there are no products in our cart, we'll prompt the user to add some
        else if (Model.OrderProducts.Count() == 0 && Model.PaymentTypeId == null)
        {
            <p>There are no products in your cart! <a asp-controller="Products" asp-action="Index">Let's go add some!</a></p>
        }
    }
</div>
<div>
    @*If there is no payment type attached (hence it's a shopping cart) AND we actually have products in the cart, give the user a Checkout button*@
    @if (Model.PaymentTypeId == null && Model.OrderProducts.Count() != 0)
    {
        <a asp-action="Edit" asp-route-id="@Model.OrderId"><button class="btn btn-primary">Checkout</button></a>
    }
</div>

Bangazon/Views/Orders/Edit.cshtml
@model Bangazon.Models.OrderViewModels.OrderEditViewModel

@{
    ViewData["Title"] = "Edit";
}

@*This view is named Edit, but it's solely used to select a Payment Type for checkout. On the backend though, it technically is editing our order*@
<h1>Checkout</h1>
@{
    //Loops through, prints every product in our order, and keeps track of the total price
    double TotalPrice = 0;
    foreach (var OrderProduct in Model.Order.OrderProducts)
    {
        <dl class="row">
            <dd class="col-sm-2">
                <a asp-action="Details" asp-route-id="@OrderProduct.ProductId">@Html.DisplayFor(model => OrderProduct.Product.Title)</a>
            </dd>
            <dt class="col-sm-10">
                @Html.DisplayFor(model => OrderProduct.Product.Price)
            </dt>
            @{
                TotalPrice += OrderProduct.Product.Price;
            }
        </dl>
    }
    <h4>Total Price: @TotalPrice.ToString("C2")</h4>
    //If the user has no payment types active on their account, prompts them to add one
    if (Model.PaymentTypes.Count() == 0)
    {
        <p> You have no payment types! Please <a asp-controller="PaymentTypes" asp-action="Create">add one here</a> to continue!</p>
    }
    //Prints out the dropdown for payment types IF the user has an active payment type
    else
    {
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Order.OrderId" />
                    <input type="hidden" asp-for="Order.DateCreated" />
                    <input type="hidden" asp-for="Order.DateCompleted" />
                    <input type="hidden" asp-for="Order.UserId" />
                    <div class="form-group">
                        <label asp-for="Order.PaymentTypeId" class="control-label">Select your payment for this order: </label>
                        <select asp-for="Order.PaymentTypeId" class="form-control" asp-items="Model.PaymentTypes"></select>
                        <span asp-validation-for="Order.PaymentTypeId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    }
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bangazon/Views/Orders/Index.cshtml
@model IEnumerable<Bangazon.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType.AccountNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>